export const countries = [
    {name: 'UNITED STATES', code: 'us'},
    {name: 'UNITED KINGDOM', code: 'gb'},
    {name: 'UNITED ARAB EMIRATES', code: 'ae'},
    {name: 'AFGHANISTAN', code: 'af'},
    {name: 'ALBANIA', code: 'al'},
    {name: 'ALGERIA', code: 'dz'},
    {name: 'AMERICAN SAMOA', code: 'as'},
    {name: 'ANDORRA', code: 'ad'},
    {name: 'ANGOLA', code: 'ao'},
    {name: 'ANGUILLA', code: 'ai'},
    {name: 'ANTARCTICA', code: 'aq'},
    {name: 'ANTIGUA AND BARBUDA', code: 'ag'},
    {name: 'ARGENTINA', code: 'ar'},
    {name: 'ARGENTINA', code: 'ar'},
    {name: 'ARMENIA', code: 'am'},
    {name: 'ARMENIA', code: 'am'},
    {name: 'ARUBA', code: 'aw'},
    {name: 'AUSTRALIA', code: 'au'},
    {name: 'AUSTRIA', code: 'at'},
    {name: 'AZERBAIJAN', code: 'az'},
    {name: 'BAHAMAS', code: 'bs'},
    {name: 'BAHRAIN', code: 'bh'},
    {name: 'BANGLADESH', code: 'bd'},
    {name: 'BARBADOS', code: 'bb'},
    {name: 'BELARUS', code: 'by'},
    {name: 'BELGIUM', code: 'be'},
    {name: 'BELIZE', code: 'bz'},
    {name: 'BENIN', code: 'bj'},
    {name: 'BERMUDA', code: 'bm'},
    {name: 'BHUTAN', code: 'bt'},
    {name: 'BOLIVIA', code: 'bo'},
    {name: 'BOSNIA AND HERZEGOVINA', code: 'ba'},
    {name: 'BOTSWANA', code: 'bw'},
    {name: 'BOUVET ISLAND', code: 'bv'},
    {name: 'BRAZIL', code: 'br'},
    {name: 'BRITISH INDIAN OCEAN TERRITORY', code: 'io'},
    {name: 'BRUNEI DARUSSALAM', code: 'bn'},
    {name: 'BULGARIA', code: 'bg'},
    {name: 'BRUNEI', code: 'bn'},
    {name: 'BURKINA FASCO', code: 'bf'},
    {name: 'BURUNDI', code: 'bi'},
    {name: 'CAMBODIA', code: 'kh'},
    {name: 'CAMEROON', code: 'cm'},
    {name: 'CANADA', code: 'ca'},
    {name: 'CAPE VERDE', code: 'cv'},
    {name: 'CAYMAN ISLANDS', code: 'ky'},
    {name: 'CENTRAL AFRICAN REPUBLIC', code: 'cf'},
    {name: 'CHAD', code: 'td'},
    {name: 'CHILE', code: 'cl'},
    {name: 'CHINA', code: 'cn'},
    {name: 'CHRISTMAS ISLAND', code: 'cx'},
    {name: 'COLOMBIA', code: 'co'},
    {name: 'COMOROS', code: 'km'},
    {name: 'CONGO', code: 'cg'},
    {name: 'COOK ISLANDS', code: 'ck'},
    {name: 'COSTA RICA', code: 'cr'},
    {name: 'DR CONGO', code: 'cd'},
    {name: 'COTE D IVOIRE', code: 'ci'},
    {name: 'IVORY COAST', code: 'ci'},
    {name: 'CROATIA', code: 'hr'},
    {name: 'JERSEY', code: 'je'},
    {name: 'CUBA', code: 'je'},
    {name: 'CYPRUS', code: 'cy'},
    {name: 'CURAÇAO', code: 'cw'},
    {name: 'CZECH REPUBLIC', code: 'cu'},
    {name: 'DENMARK', code: 'dk'},
    {name: 'DJIBOUTI', code: 'dj'},
    {name: 'DOMINICA', code: 'dm'},
    {name: 'DOMINICAN REPUBLIC', code: 'do'},
    {name: 'EAST TIMOR', code: 'tp'},
    {name: 'ECUADOR', code: 'ec'},
    {name: 'EGYPT', code: 'eg'},
    {name: 'EL SALVADOR', code: 'sv'},
    {name: 'EQUATORIAL GUINEA', code: 'gq'},
    {name: 'ERITREA', code: 'er'},
    {name: 'ESTONIA', code: 'ee'},
    {name: 'ETHIOPIA', code: 'et'},
    {name: 'FALK', code: 'fk'},
    {name: 'FAROE ISLANDS', code: 'fo'},
    {name: 'FIJI', code: 'fj'},
    {name: 'FINLAND', code: 'fi'},
    {name: 'FRANCE', code: 'fr'},
    {name: 'FRENCH GUIANA', code: 'eegf'},
    {name: 'FRENCH POLYNESIA', code: 'pf'},
    {name: 'FRENCH SOUTHERN TERRITORIES', code: 'tf'},
    {name: 'GABON', code: 'ga'},
    {name: 'GAMBIA', code: 'gm'},
    {name: 'GEORGIA', code: 'ge'},
    {name: 'GERMANY', code: 'de'},
    {name: 'GHANA', code: 'gh'},
    {name: 'GIBRALTAR', code: 'gi'},
    {name: 'GREECE', code: 'gr'},
    {name: 'GREENLAND', code: 'gl'},
    {name: 'GRENADA', code: 'gd'},
    {name: 'GUADELOUPE', code: 'gp'},
    {name: 'GUAM', code: 'gu'},
    {name: 'GUATEMALA', code: 'gt'},
    {name: 'GUINEA', code: 'gn'},
    {name: 'GUINEA-BISSAU', code: 'gw'},
    {name: 'GUYANA', code: 'gy'},
    {name: 'HAITI', code: 'ht'},
    {name: 'HEARD ISLAND AND MCDONALD ISLANDS', code: 'hm'},
    {name: 'HOLY', code: 'va'},
    {name: 'VATICAN', code: 'va'},
    {name: 'HONDURAS', code: 'hn'},
    {name: 'TIMOR', code: 'tl'},
    {name: 'TIMOR LESTE', code: 'tl'},
    {name: 'HONG KONG', code: 'hk'},
    {name: 'HUNGARY', code: 'hu'},
    {name: 'ICELAND', code: 'is'},
    {name: 'INDIA', code: 'in'},
    {name: 'INDONESIA', code: 'id'},
    {name: 'IRAN', code: 'ir'},
    {name: 'IRAQ', code: 'iq'},
    {name: 'IRELAND', code: 'ie'},
    {name: 'ISRAEL', code: 'il'},
    {name: 'ITALY', code: 'it'},
    {name: 'JAMAICA', code: 'jm'},
    {name: 'JAPAN', code: 'jp'},
    {name: 'JORDAN', code: 'jo'},
    {name: 'KAZAKHSTAN', code: 'kz'},
    {name: 'KENYA', code: 'ke'},
    {name: 'KIRIBATI', code: 'ki'},
    {name: 'KOSOVO', code: 'xk'},
    {name: 'KOREA DEMOCRATIC PEOPLES REPUBLIC', code: 'kp'},
    {name: 'KOREA REPUBLIC', code: 'kr'},
    {name: 'KUWAIT', code: 'kw'},
    {name: 'NORTH KOREA', code: 'kp'},
    {name: 'SOUTH KOREA', code: 'kr'},
    {name: 'KYRGYZSTAN', code: 'kg'},
    {name: 'LAO PEOPLES DEMOCRATIC REPUBLIC', code: 'la'},
    {name: 'LATVIA', code: 'lv'},
    {name: 'LAOS', code: 'la'},
    {name: 'LEBANON', code: 'lb'},
    {name: 'LESOTHO', code: 'ls'},
    {name: 'LIBERIA', code: 'lr'},
    {name: 'LIBYAN ARAB JAMAHIRIYA', code: 'ly'},
    {name: 'LIECHTENSTEIN', code: 'li'},
    {name: 'LIBYA', code: 'ly'},
    {name: 'LITHUANIA', code: 'lt'},
    {name: 'LUXEMBOURG', code: 'lu'},
    {name: 'MACAU', code: 'mo'},
    {name: 'MACEDONIA', code: 'mk'},
    {name: 'MADAGASCAR', code: 'mg'},
    {name: 'MALAWI', code: 'mw'},
    {name: 'MALAYSIA', code: 'my'},
    {name: 'MALDIVES', code: 'mv'},
    {name: 'MALI', code: 'ml'},
    {name: 'MALTA', code: 'mt'},
    {name: 'MARSHALL ISLANDS', code: 'mh'},
    {name: 'MARTINIQUE', code: 'mq'},
    {name: 'MAURITANIA', code: 'mr'},
    {name: 'MAURITIUS', code: 'mu'},
    {name: 'MAYOTTE', code: 'yt'},
    {name: 'MEXICO', code: 'mx'},
    {name: 'MICRONESIA', code: 'fm'},
    {name: 'MOLDOVA', code: 'md'},
    {name: 'MONACO', code: 'mc'},
    {name: 'MONGOLIA', code: 'mn'},
    {name: 'MONTSERRAT', code: 'ms'},
    {name: 'MOROCCO', code: 'ma'},
    {name: 'MOZAMBIQUE', code: 'mz'},
    {name: 'MYANMAR', code: 'mm'},
    {name: 'MONTENEGRO', code: 'me'},
    {name: 'NAMIBIA', code: 'na'},
    {name: 'NAURU', code: 'nr'},
    {name: 'NEPAL', code: 'np'},
    {name: 'NETHERLAND', code: 'nl'},
    {name: 'NETHERLAND ANTILLES', code: 'an'},
    {name: 'NEW CALEDONIA', code: 'nc'},
    {name: 'NEW ZEALAND', code: 'nz'},
    {name: 'NICARAGUA', code: 'ni'},
    {name: 'NIGER', code: 'ne'},
    {name: 'NIGERIA', code: 'ng'},
    {name: 'NIUE', code: 'nu'},
    {name: 'NORFOLK ISLAND', code: 'nf'},
    {name: 'NORTHERN MARIANA ISLANDS', code: 'mp'},
    {name: 'NORWAY', code: 'no'},
    {name: 'OMAN', code: 'om'},
    {name: 'PAKISTAN', code: 'pk'},
    {name: 'PALAU', code: 'pw'},
    {name: 'PALESTINE', code: 'ps'},
    {name: 'PANAMA', code: 'pa'},
    {name: 'PAPUA NEW GUINEA', code: 'pg'},
    {name: 'PARAGUAY', code: 'py'},
    {name: 'PERU', code: 'pe'},
    {name: 'PHILIPPINES', code: 'ph'},
    {name: 'PITCAIRN', code: 'pn'},
    {name: 'POLAND', code: 'pl'},
    {name: 'PORTUGAL', code: 'pt'},
    {name: 'PUERTO RICO', code: 'pr'},
    {name: 'QATAR', code: 'qa'},
    {name: 'REUNION', code: 're'},
    {name: 'ROMANIA', code: 'ro'},
    {name: 'RUSSIA', code: 'ru'},
    {name: 'RWANDA', code: 'rw'},
    {name: 'SAINT HELENA', code: 'sh'},
    {name: 'SAINT KITTS AND NEVIS', code: 'kn'},
    {name: 'SAINT LUCIA', code: 'lc'},
    {name: 'SAINT PIERRE AND MIQUELON', code: 'pm'},
    {name: 'SAINT VINCENT AND THE GRENADINES', code: 'vc'},
    {name: 'SAMOA', code: 'ws'},
    {name: 'SAN MARINO', code: 'sm'},
    {name: 'SAO TOME AND PRINCIPE', code: 'st'},
    {name: 'SAUDI  ARABIA', code: 'sa'},
    {name: 'SENEGAL', code: 'sn'},
    {name: 'SEYCHELLES', code: 'sc'},
    {name: 'SIERRA LEONE', code: 'sl'},
    {name: 'SINGAPORE', code: 'sg'},
    {name: 'SLOVAKIA', code: 'sk'},
    {name: 'SLOVENIA', code: 'si'},
    {name: 'SOLOMON ISLANDS', code: 'sb'},
    {name: 'SOMALIA', code: 'so'},
    {name: 'SOUTH AFRICA', code: 'za'},
    {name: 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', code: 'gs'},
    {name: 'SPAIN', code: 'es'},
    {name: 'SRI LANKA', code: 'lk'},
    {name: 'SUDAN', code: 'sd'},
    {name: 'SURINAME', code: 'sr'},
    {name: 'SVALBARD AND JAN MAYEN', code: 'sj'},
    {name: 'SWAZILAND', code: 'sz'},
    {name: 'ESWATINI', code: 'sz'},
    {name: 'SWEDEN', code: 'se'},
    {name: 'SWITZERLAND', code: 'ch'},
    {name: 'SYRIAN ARAB REPUBLIC', code: 'sy'},
    {name: 'SYRIA', code: 'sy'},
    {name: 'TAIWAN, PROVINCE OF CHINA', code: 'tw'},
    {name: 'TAJIKISTAN', code: 'tj'},
    {name: 'TANZANIA', code: 'tz'},
    {name: 'THAILAND', code: 'th'},
    {name: 'TOGO', code: 'tg'},
    {name: 'TOKELAU', code: 'tk'},
    {name: 'TONGA', code: 'to'},
    {name: 'TAIWAN	', code: 'tw'},
    {name: 'TRINIDAD AND TOBAGO', code: 'tt'},
    {name: 'TUNISIA', code: 'tn'},
    {name: 'TURKEY', code: 'tr'},
    {name: 'TURKMENISTAN', code: 'tm'},
    {name: 'TURKS AND CAICOS ISLANDS', code: 'tc'},
    {name: 'TUVALU', code: 'tv'},
    {name: 'UGANDA', code: 'ug'},
    {name: 'UKRAINE', code: 'ua'},
    {name: 'UNITED STATES OF AMERICA', code: 'us'},
    {name: 'URUGUAY', code: 'uy'},
    {name: 'UZBEKISTAN', code: 'uz'},
    {name: 'VANUATU', code: 'vu'},
    {name: 'VENEZUELA', code: 've'},
    {name: 'VIETNAM', code: 'vn'},
    {name: 'VIRGIN ISLANDS, BRITISH', code: 'vg'},
    {name: 'VIRGIN ISLANDS, U.S.', code: 'vi'},
    {name: 'WALLIS AND FUTUNA', code: 'wf'},
    {name: 'WESTERN SAHARA', code: 'eh'},
    {name: 'YEMEN', code: 'ye'},
    {name: 'YUGOSLAVIA', code: 'yu'},
    {name: 'ZAMBIA', code: 'zm'},
    {name: 'ZIMBABWE', code: 'zw'},
    {name: 'SERBIA', code: 'rs'},
    {name: 'SAINT MARTIN(DUTCH)', code: 'sx'},
    {name: 'WORLD', code: 'wo'}
];